from .customer_account import *
from .homepage import *
from .index import *
from .seller_account import * 
from .seller_profile import *
from .search import *
from .seller_signup import *
from .seller_update_account import *
from .seller_signin import *
from .seller_update_profile import *
from .seller_create_profile import *
from .seller_delete_profile import *
from .customer_signup import *
from .customer_signin import *
from .customer_update_account import *
from .forms import *
from .send_message import *