from .customer_account import *
from .homepage import *
from .index import *
from .seller_account import * 
from .seller_profile import *
from .search import *
from .seller_signup import *
from .seller_update_account import *
from .seller_signin import *
from .seller_update_profile import *
from .seller_create_profile import *
from .seller_delete_profile import *
from .customer_signup import *
from .customer_signin import *
from .customer_update_account import *
from .forms import *
from .send_message import *
from .get_chat import *
from .explore_chats import *
from .add_review import *
from .start_service import *
from .end_service import *
from .service_requests import *
from .active_services import *
from .accept_service import *
from .delete_service import *
from .explore_reviews import *
from .pause_profile import *
from .resume_profile import *