# Generated by Django 4.2.5 on 2024-06-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
