# Generated by Django 4.2.5 on 2024-06-25 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial2'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='chat',
            name='person2_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
