# Generated by Django 4.2.5 on 2024-06-26 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_customer_account_chat_person2_id_seller_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.IntegerField(null=True)),
                ('person2_id', models.CharField(max_length=50, null=True)),
                ('rate', models.IntegerField(default=0)),
                ('comment', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deal_With',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.IntegerField(null=True)),
                ('person2_id', models.CharField(max_length=50, null=True)),
                ('is_accepted', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('accept_time', models.DateField(null=True)),
                ('end_time', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
