# Generated by Django 4.2.5 on 2024-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_customer_account_img_seller_account_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_message',
            field=models.TextField(blank=True, max_length=900000, null=True),
        ),
    ]
