# Generated by Django 4.2.5 on 2024-06-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_message_image_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal_with',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
